title: Jiajun Sun's Homepage
page-top-title: 孙嘉骏 | Sun Jiajun
top-section-bg-text: Unexpected Encounters, Adapt to Circumstances
home-subtitle: Jiajun Sun
copyright-text: '&copy; Copyright 2026 Jiajun Sun.'
