title: Jiajun Sun's Homepage
page-top-title: Jiajun Sun
top-section-bg-text: Unexpected Encounters, Adapt to Circumstances
home-subtitle: Jiajun Sun
copyright-text: '&copy; Jiajun Sun 2025. All Rights Reserved.'
